name: funprono_lib
description: A package for Back and front for FunProno application.
version: 5.0.8
homepage: https://app.funprono.com
documentation: https://github.com/jbdujardin/funprono_lib
repository: https://github.com/jbdujardin/funprono_lib
issue_tracker: https://github.com/jbdujardin/funprono_lib/issues
publish_to: https://onepub.dev/api/kabbxpsdav/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_appwrite: ^11.0.3
  collection: ^1.19.0
  freezed_annotation: ^2.4.4
  http: ^1.0.0
  json_annotation: ^4.9.0
dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.25.8
