name: funprono_lib
description: A package for Back and front for FunProno application.
version: 3.2.1
homepage: https://app.funprono.com
documentation: https://github.com/jbdujardin/funprono_lib
repository: https://github.com/jbdujardin/funprono_lib
issue_tracker: https://github.com/jbdujardin/funprono_lib/issues
publish_to: https://onepub.dev/api/kabbxpsdav/

environment: 
  sdk: '>=2.17.0 <4.0.0'

dependencies: 
  collection: any
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.7.0
dev_dependencies: 
  build_runner: ^2.4.6
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  lints: ^2.0.1
  test: ^1.24.3
